# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c05c8baa7ef387a5dff2e7aa06457b0dd1876c8efd8bb16985e79a7d23bdd92ef3582fb453412d75a0fd1be653974c8144ea3103c4af5914531eab873855e41a
  jwt_secret: a35c522e698f04484bfacd9f757b5ac61566c30ef6d6a897e4686b1d8415636b5dbcc2bc3fc8382ce844a0d52600b8a2e846a49eec92631d43bc0bf775fc3c31

test:
  secret_key_base: 79f59e094c9512b51d55149aea7905484499ed44f82bcc8a5b3cd9c9bbdf3f6bb7034530df8dc1eae0438eaef78adf67c8c278d914ba6ba1ee7acea184b15e7e
  jwt_secret: aed3136131a18499cacc7121c7b95ab5f35c5d090d0fc8fe664192021b9d2bcb3c5a5e7f150d8f73b82d3c61797c998a94eebc78ac8dbf5f69d9a9227364e940

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_secret: <%= ENV["JWT_SECRET"] %>
